import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { logo } from '../assets'
import Header from '@/components/Header'
import { useState } from 'react'
import FormField from '@/components/FormField'
import Loader from '@/components/Loader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [loading, setLoading] = useState(false)
  const [allPost, setAllPost] = useState(null)
  const [searchText, setSearchText] = useState('')

  return (
    <main>
      <section className='max-w-7xl mx-auto'>
        <div>
          <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
          <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E-AI</p>
        </div>
        <div className='mt-16 '>
          <FormField />
        </div>
        <div className='mt-10'>
          {loading ?
            <div className='flex justify-center items-center'>
              <Loader />
            </div> : (<>{searchText && <h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing results for <span className='text-[#222328]'>{searchText}</span></h2>}</>)}
          
        </div>
      </section>
    </main>
  )
}
